books/urls.py
from django.urls import path

from books.views import books_list_view, book_detail_view, download_book_view

app_name = 'books'

urlpatterns = [
    path('', books_list_view, name='list'),
    path('<int:pk>/', book_detail_view, name='detail'),
    path('download/<int:pk>/', download_book_view, name='download'),
]

conf/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('login/', include('courses.urls', namespace='courses'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/urls.py
from django.urls import path

from books.views import books_list_view
from courses.views import login_view, courses_view

app_name = 'courses'

urlpatterns = [
    path('list/', courses_view, name='list'),
    path('', login_view, name='login'),

]

books/models.py
from django.db import models


class BookModel(models.Model):
    image = models.ImageField(upload_to='books-images', null=True)
    author = models.CharField(max_length=128)
    title = models.CharField(max_length=255)
    info = models.TextField()
    pages = models.IntegerField()
    ebook = models.FileField(upload_to='ebooks', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.title

    def __repr__(self):
        return self.title

    class Meta:
        verbose_name = 'book'
        verbose_name_plural = 'books'

courses/models.py
from django.db import models


class CoursesModel(models.Model):
    full_name = models.CharField(max_length=123)
    phone_number = models.CharField(max_length=13)
    age = models.IntegerField()

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'courses'
        verbose_name_plural = 'coursess'

courses/forms.py
from django import forms


class CoursesForm(forms.Form):
    full_name = forms.CharField()
    phone_number = forms.CharField()
    age = forms.IntegerField()

books/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import BookModel


def books_list_view(request):
    books = BookModel.objects.all()
    q = request.GET.get('q')
    if q:
        books = books.filter(title__icontains=q)

    context = {'books': books}
    return render(request, 'books.html', context)


def book_detail_view(request, pk):
    book = BookModel.objects.filter(id=pk).first()
    if book:
        context = {'book': book}
        return render(request, 'book-detail.html', context)
    else:
        return HttpResponse('Book not found')


def download_book_view(request, pk):
    book = BookModel.objects.filter(id=pk).first()

    if book:
        file_path = str(book.ebook)
        with open(file_path, 'rb') as f:
            response = HttpResponse(f.read(), content_type='application/pdf')
            return response
    else:
        return HttpResponse("Book not found")

courses/views.py
from django.shortcuts import render, redirect

from courses.forms import CoursesForm
from courses.models import CoursesModel


def login_view(request):
    if request.method == 'POST':
        form = CoursesForm(request.POST)
        if form.is_valid():
            CoursesModel.objects.create(
                full_name=form.cleaned_data['full_name'],
                phone_number=form.cleaned_data['phone_number'],
                age=form.cleaned_data['age'],
            )
            return redirect('courses:login')
    else:
        form = CoursesForm()
        context = {
            'form': form
        }
        return render(request, 'login.html', context)


def courses_view(request):
    result = CoursesModel.objects.all()
    context = {
        'result': result
    }
    return render(request, 'courses.html', context)

templates/book-detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Detail</title>
    <link rel="stylesheet" href="{% static 'css/book-detail.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto ">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'books:list' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'books:list' %}">
                <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>

    </div>

</nav>
    <div class="container">
        <div class="book-details">
            <div class="book-image">
                <img src="{{ book.image.url }}" alt="Book Cover">
            </div>
            <div class="book-info">
                <hr>
                <h1>{{ book.title }} | {{ book.author }}</h1>
                <div class="description">
                    <p>{{ book.info }}</p>
                </div>
                <hr>
            </div>
        </div>

        <div class="add-comment">

            <h3>Add a comment</h3>
            <form>
                <textarea name="comment" id="comment" rows="4" placeholder="Write your comment here..." required></textarea>
                <button type="submit">Submit</button>
            </form>
        </div>

        <div class="comments">
            <h2>Comments</h2>
            <div class="comment">
                <p class="comment-text">This book is amazing! I couldn't put it down.</p>
                <p class="comment-author">- John Doe</p>
            </div>
            <div class="comment">
                <p class="comment-text">One of the best classics I've ever read.</p>
                <p class="comment-author">- Jane Smith</p>
            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/books.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/stayle.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto ">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                value="{{ request.GET.q }}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>

    </div>

</nav>
<div class="container mt-3">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="10%" scope="col">#</th>
            <th width="30%" scope="col">Author</th>
            <th width="50%" scope="col">Book title</th>
            <th width="10%" scope="col">Download</th>
        </tr>
        </thead>
        <tbody>
        {% for book in books %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>

                <td>
                    <a style="color: black" href="{% url 'books:detail' pk=book.id %}">
                        {{ book.author }}
                    </a>

                </td>

                <td>
                    <a style="color: black" href="{% url 'books:detail' pk=book.id %}">
                        {{ book.title }}
                    </a>
                </td>
                <td>
                    <a target="_blank" href="{% url 'books:download' pk=book.id %}">
                        <i class="fa-solid fa-cloud-arrow-down ml-4"></i>
                    </a>

                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<h4 class="table mt-5" style="text-align: center">
    <a href="login">Royxatdan o'tish</a>
</h4>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/courses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><i style="color: #006b1b;">Ism Familya</i></th>
      <th scope="col"><i style="color: #006b1b;">Telfon Raqam</i></th>
      <th scope="col"><i style="color: #006b1b;">Yosh</i></th>
    </tr>
  </thead>
  <tbody>
  {% for i in result %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ i.full_name }}</td>
      <td>{{ i.phone_number }}</td>
      <td>{{ i.age }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<h4 class="table mt-5" style="text-align: center" >
    <a href="{% url 'courses:login' %} " style="text-align: center"><i style="color: #4ac1f7">Ortga qaytish</i></a>
</h4>





<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"></script>

</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

<!-- partial:index.partial.html -->
<section class="container">
    <div class="login-container">
        <div class="circle circle-one"></div>
        <div class="form-container">
            <img src="https://raw.githubusercontent.com/hicodersofficial/glassmorphism-login-form/master/assets/illustration.png" alt="illustration" class="illustration" />
            <h1 class="opacity">LOGIN</h1>
            <form method="post" action="{% url 'courses:login' %}">
                {% csrf_token %}
                <input name="full_name" type="text" placeholder="full_name" style="color: black"/>
                <input name="phone_number" type="text" placeholder="phone_number" style="color: black"/>
                <input name="age" type="number" placeholder="age" style="color: black"/>
                <button><a href="{% url 'courses:login' %}"></a>Submit</button> <br>
                <br>
                <a href="{% url 'courses:list' %}">Royxatdan o'tkanlar</a>
                <a href="{% url 'books:list' %}">Ortga qaytish</a>
            </form>
        </div>
        <div class="circle circle-two"></div>
    </div>
    <div class="theme-btn-container"></div>
</section>




<!-- partial -->
<script src="./script.js"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>